[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.149.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_VERSION = "0.149.1"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.149.1"

[context.branch-deploy.environment]
HUGO_VERSION = "0.149.1"

# Headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
for = "/css/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/js/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules (add as needed)
# [[redirects]]
# from = "/old-path"
# to = "/new-path"
# status = 301

# Plugin configuration (optional)
# [[plugins]]
# package = "netlify-plugin-hugo-cache-resources"

# Build command for different contexts
[context.production]
command = "hugo --gc --minify"

[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
